### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by avichalp**
Ref: #398

### CODE REVIEW

**Comment by rudolfs** [comment]
👍

**Comment by kelada** [comment]
This looks good, I'd like QA to run through this PR before we merge it in (if it hasn't happened already). @calumljohnston @TheMeaningfulEngineer

**Comment by TheMeaningfulEngineer** [comment]
Will take on this after the SD deadline.
Need to merge it into master, rebase the whole BT stuff on it and than run QA.

Taking on the merging.

**Comment by kelada** [comment]
I suspect you need to rebase this branch on the latest master. Please resolve the Travis issues. I'd like to test and merge this in next week 👍

**Comment by avichalp** [comment]
@kelada : This is rebased with latest master. There is a failing test in latest master and that is why the travis build is failing.
I have created a [PR](https://github.com/getsenic/senic-hub/pull/422) to fix the failing test by  changing the test according to the new Bluetooth code.

After that PR is merged in master and this gets rebased again the Travis build will work fine.

**Comment by kelada** [comment]
@calumljohnston tested this PR.

**Pull request merged**
