### PR TITLE
Cleanup docs

### PR DESCRIPTION
**Pull request by tomster**
This allows setting up a hub for development from scratch

### CODE REVIEW

**Comment by TheMeaningfulEngineer** [comment]
Travis build result link not rendered as image.

**Comment by TheMeaningfulEngineer** [comment]
Thinking like someone who just want's to get up and running, would just a set of commands that I can copy paste without reading the descriptions.

Like here: https://github.com/TheMeaningfulEngineer/senic-infrastructure/blob/docs-cleanup2/docs/osbuild.rst

**Comment by TheMeaningfulEngineer** [comment]
There is `tox` dependency to run `make` the first time.

```
$ make
tox -e develop --notest
make: tox: Command not found
Makefile:10: recipe for target 'venv/bin/pserve' failed
make: *** [venv/bin/pserve] Error 127

```

**Comment by tomster** [comment]
For some reason the commit i added to resolve the conflicts never showed up here, despite pushing and doublechecking the target, so i merged locally and pushed to master

**Pull request closed without merging**
