### PR TITLE
Add nuimo battery level notification in nuimo_app

### PR DESCRIPTION
**Pull request by commento**
it requires the nuimo module related to this PR https://github.com/getsenic/nuimo-linux-python/pull/34
The battery level is now notified in nuimo_app and saved in the configuration file.
This approach is related to the issues with the battery level implementation in the backend app
(see PR  #327)

### CODE REVIEW

**Comment by kelada** [comment]
Are there any performance impacts of this PR?

**Comment by commento** [comment]
no, in terms of time to process the request.

This is the PR code for confnuimos endpoint:
schermata 2017-10-12 alle 14 04 44 2
schermata 2017-10-12 alle 14 05 36 2

this is the master:
schermata 2017-10-12 alle 14 07 18 2

**Comment by kelada** [comment]
Good, I'll test this when I'm in the office next and hopefully merge everything in 👍

**Comment by kelada** [comment]
This feature appears to work as advertised.
screen shot 2017-10-16 at 10 42 41

**Pull request merged**
