### PR TITLE
Add method to get process status

### PR DESCRIPTION
**Pull request by neelotpalnag**
Handles cases when Nuimos are removed rapidly, without allowing the nuimo_app to restart completely.
Added a method to get the status of the process.

### CODE REVIEW

**Comment by neelotpalnag** [comment]
Fix for PR #382

**Comment by kelada** [comment]
This doesn't appear to work. Removing Nuimos quickly one after the other doesn't disconnect them at all. Only on reboot do they disconnect.

If a solution can't be found on the backend, a short term fix can be made on the frontend.

**Comment by neelotpalnag** [comment]
I'd request applying a frontend fix because it seems to be spitting out errors constantly in the backend. The errors have been handled with try-catch,  but a permanent solution couldn't be found ATM

**Comment by kelada** [comment]
Please test again and merge in

**Comment by neelotpalnag** [comment]
Tested. Closing.

**Pull request merged**
